require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")

vim.cmd("set termguicolors")
vim.cmd("let g:gruvbox_contrast_dark = 'hard'")
vim.cmd("let g:gruvbox_contrast_light = 'hard'")
vim.cmd("colorscheme gruvbox")
vim.cmd("hi LspCxxHlGroupMemberVariable guifg=#83a598")
